springdoc:
  # ??? ??? ??(??? ??? ??? API ??? ????)
  packages-to-scan: com.ohgiraffers.restapi.section05
  # consumes : ?? ??? ??, produces : ?? ??? ??
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
